#shapeshifting utils

def boat_cells_from_parent(boat_location, parent_latch_name, child_latch_name):
    x1, y1 = boat_location[0]
    x2, y2 = boat_location[1]

    if parent_latch_name == "bow_male":
        if child_latch_name == "stern_female":
            if y2 > y1:
                boat_cell1 = (x2, y2+1)
                boat_cell2 = (x2, y2+2)
            elif y2 < y1:
                boat_cell1 = (x2, y2-1)
                boat_cell2 = (x2, y2-2)
            elif x2 > x1:
                boat_cell1 = (x2+1, y2)
                boat_cell2 = (x2+2, y2)
            elif x2 < x1:
                boat_cell1 = (x2-1, y2)
                boat_cell2 = (x2-2, y2)
        elif child_latch_name == "port_female_bottom":
            if y2 > y1:
                boat_cell1 = (x2, y2+1)
                boat_cell2 = (x2-1, y2+1)
            elif y2 < y1:
                boat_cell1 = (x2, y2-1)
                boat_cell2 = (x2+1, y2-1)
            elif x2 > x1:
                boat_cell1 = (x2+1, y2)
                boat_cell2 = (x2+1, y2+1)
            elif x2 < x1:
                boat_cell1 = (x2-1, y2)
                boat_cell2 = (x2-1, y2-1)
        elif child_latch_name == "port_female_top":
            if y2 > y1:
                boat_cell1 = (x2, y2+1)
                boat_cell2 = (x2+1, y2+1)
            elif y2 < y1:
                boat_cell1 = (x2, y2-1)
                boat_cell2 = (x2-1, y2-1)
            elif x2 > x1:
                boat_cell1 = (x2+1, y2)
                boat_cell2 = (x2+1, y2-1)
            elif x2 < x1:
                boat_cell1 = (x2-1, y2)
                boat_cell2 = (x2-1, y2+1)
        else:
            return ((0,0), (0,0), False)

    elif parent_latch_name == "starboard_male_top":
        if child_latch_name == "stern_female":
            if y2 > y1:
                boat_cell1 = (x2+1, y2)
                boat_cell2 = (x2+2, y2)
            elif y2 < y1:
                boat_cell1 = (x2-1, y2)
                boat_cell2 = (x2-2, y2)
            elif x2 > x1:
                boat_cell1 = (x2, y2-1)
                boat_cell2 = (x2, y2-2)
            elif x2 < x1:
                boat_cell1 = (x2, y2+1)
                boat_cell2 = (x2, y2+2)
        elif child_latch_name == "port_female_bottom":
            if y2 > y1:
                boat_cell1 = (x2+1, y2)
                boat_cell2 = (x2+1, y2+1)
            elif y2 < y1:
                boat_cell1 = (x2-1, y2)
                boat_cell2 = (x2-1, y2-1)
            elif x2 > x1:
                boat_cell1 = (x2, y2-1)
                boat_cell2 = (x2+1, y2-1)
            elif x2 < x1:
                boat_cell1 = (x2, y2+1)
                boat_cell2 = (x2-1, y2+1)
        elif child_latch_name == "port_female_top":
            if y2 > y1:
                boat_cell1 = (x2+1, y2-1)
                boat_cell2 = (x2+1, y2)
            elif y2 < y1:
                boat_cell1 = (x2-1, y2+1)
                boat_cell2 = (x2-1, y2)
            elif x2 > x1:
                boat_cell1 = (x2-1, y2-1)
                boat_cell2 = (x2, y2-1)
            elif x2 < x1:
                boat_cell1 = (x2+1, y2+1)
                boat_cell2 = (x2, y2+1)
        else:
            return ((0,0), (0,0), False)


    elif parent_latch_name == "starboard_male_bottom":
        if child_latch_name == "stern_female":
            if y2 > y1:
                boat_cell1 = (x1+1, y1)
                boat_cell2 = (x1+2, y1)
            elif y2 < y1:
                boat_cell1 = (x1-1, y1)
                boat_cell2 = (x1-2, y1)
            elif x2 > x1:
                boat_cell1 = (x1, y1-1)
                boat_cell2 = (x1, y1-2)
            elif x2 < x1:
                boat_cell1 = (x1, y1+1)
                boat_cell2 = (x1, y1+2)
        elif child_latch_name == "port_female_bottom":
            if y2 > y1:
                boat_cell1 = (x1+1, y1)
                boat_cell2 = (x1+1, y1+1)
            elif y2 < y1:
                boat_cell1 = (x1-1, y1)
                boat_cell2 = (x1-1, y1-1)
            elif x2 > x1:
                boat_cell1 = (x1, y1-1)
                boat_cell2 = (x1+1, y1-1)
            elif x2 < x1:
                boat_cell1 = (x1, y1+1)
                boat_cell2 = (x1-1, y1+1)
        elif child_latch_name == "port_female_top":
            if y2 > y1:
                boat_cell1 = (x1+1, y1)
                boat_cell2 = (x1+1, y1+1)
            elif y2 < y1:
                boat_cell1 = (x1-1, y1)
                boat_cell2 = (x1-1, y1-1)
            elif x2 > x1:
                boat_cell1 = (x1, y1-1)
                boat_cell2 = (x1+1, y1-1)
            elif x2 < x1:
                boat_cell1 = (x1, y1+1)
                boat_cell2 = (x1-1, y1+1)
        else:
            return ((0,0), (0,0), False)



    elif parent_latch_name == "stern_female":
        if child_latch_name == "bow_male":
            if y2 > y1:
                boat_cell1 = (x1, y1-2)
                boat_cell2 = (x1, y1-1)
            elif y2 < y1:
                boat_cell1 = (x1, y1+2)
                boat_cell2 = (x1, y1+1)
            elif x2 > x1:
                boat_cell1 = (x1-2, y1)
                boat_cell2 = (x1-1, y1)
            elif x2 < x1:
                boat_cell1 = (x1+2, y1)
                boat_cell2 = (x1+1, y1)
        elif child_latch_name == "starboard_male_bottom":
            if y2 > y1:
                boat_cell1 = (x1, y1-1)
                boat_cell2 = (x1-1, y1-1)
            elif y2 < y1:
                boat_cell1 = (x1, y1+1)
                boat_cell2 = (x1+1, y1+1)
            elif x2 > x1:
                boat_cell1 = (x1-1, y1)
                boat_cell2 = (x1-1, y1+1)
            elif x2 < x1:
                boat_cell1 = (x1+1, y1)
                boat_cell2 = (x1+1, y1-1)
        elif child_latch_name == "starboard_male_top":
            if y2 > y1:
                boat_cell1 = (x1, y1-1)
                boat_cell2 = (x1+1, y1-1)
            elif y2 < y1:
                boat_cell1 = (x1, y1+1)
                boat_cell2 = (x1-1, y1+1)
            elif x2 > x1:
                boat_cell1 = (x1-1, y1)
                boat_cell2 = (x1-1, y1-1)
            elif x2 < x1:
                boat_cell1 = (x1+1, y1)
                boat_cell2 = (x1+1, y1+1)
        else:
            return ((0,0), (0,0), False)

    elif parent_latch_name == "port_female_bottom":
        if child_latch_name == "bow_male":
            if y2 > y1:
                boat_cell1 = (x1-1, y1)
                boat_cell2 = (x1-2, y1)
            elif y2 < y1:
                boat_cell1 = (x1+1, y1)
                boat_cell2 = (x1+2, y1)
            elif x2 > x1:
                boat_cell1 = (x1, y1+1)
                boat_cell2 = (x1, y1+2)
            elif x2 < x1:
                boat_cell1 = (x1, y1-1)
                boat_cell2 = (x1, y1-2)
        elif child_latch_name == "starboard_male_bottom":
            if y2 > y1:
                boat_cell1 = (x1-1, y1)
                boat_cell2 = (x1-1, y1+1)
            elif y2 < y1:
                boat_cell1 = (x1+1, y1)
                boat_cell2 = (x1+1, y1-1)
            elif x2 > x1:
                boat_cell1 = (x1, y1+1)
                boat_cell2 = (x1+1, y1+1)
            elif x2 < x1:
                boat_cell1 = (x1, y1-1)
                boat_cell2 = (x1-1, y1-1)
        elif child_latch_name == "starboard_male_top":
            if y2 > y1:
                boat_cell1 = (x1-1, y1-1)
                boat_cell2 = (x1-1, y1)
            elif y2 < y1:
                boat_cell1 = (x1+1, y1+1)
                boat_cell2 = (x1+1, y1)
            elif x2 > x1:
                boat_cell1 = (x1-1, y1+1)
                boat_cell2 = (x1, y1+1)
            elif x2 < x1:
                boat_cell1 = (x1+1, y1-1)
                boat_cell2 = (x1, y1-1)
        else:
            return ((0,0), (0,0), False)

    elif parent_latch_name == "port_female_top":
        if child_latch_name == "bow_male":
            if y2 > y1:
                boat_cell1 = (x2-1, y2)
                boat_cell2 = (x2-2, y2)
            elif y2 < y1:
                boat_cell1 = (x2+1, y2)
                boat_cell2 = (x2+2, y2)
            elif x2 > x1:
                boat_cell1 = (x2, y2+1)
                boat_cell2 = (x2, y2+2)
            elif x2 < x1:
                boat_cell1 = (x2, y2-1)
                boat_cell2 = (x2, y2-2)
        elif child_latch_name == "starboard_male_bottom":
            if y2 > y1:
                boat_cell1 = (x2-1, y2)
                boat_cell2 = (x2-1, y2+1)
            elif y2 < y1:
                boat_cell1 = (x2+1, y2)
                boat_cell2 = (x2+1, y2-1)
            elif x2 > x1:
                boat_cell1 = (x2, y2+1)
                boat_cell2 = (x2+1, y2+1)
            elif x2 < x1:
                boat_cell1 = (x2, y2-1)
                boat_cell2 = (x2-1, y2-1)
        elif child_latch_name == "starboard_male_top":
            if y2 > y1:
                boat_cell1 = (x2-1, y2-1)
                boat_cell2 = (x2-1, y2)
            elif y2 < y1:
                boat_cell1 = (x2+1, y2+1)
                boat_cell2 = (x2+1, y2)
            elif x2 > x1:
                boat_cell1 = (x2-1, y2+1)
                boat_cell2 = (x2, y2+1)
            elif x2 < x1:
                boat_cell1 = (x2+1, y2-1)
                boat_cell2 = (x2, y2-1)
        else:
            return ((0,0), (0,0), False)
    return (boat_cell1, boat_cell2, True)

